### ISSUE TITLE
google play

### ISSUE THREAD

**Issue by yinzhen1989** [FSpaceCore/SpaceCore#35]
引擎能上google play么？

**Comment by jack20209527** [comment]
没上去，总报错，发邮件了但没回复，让给sdk的清单文件的debug改成false，一直不回复，包也总上不了架。

**Comment by FSpaceCore** [comment]
需要自行覆盖一下xml中的debuggable

**Comment by dongbeicxy** [comment]
> 没上去，总报错，发邮件了但没回复，让给sdk的清单文件的debug改成false，一直不回复，包也总上不了架。
我在Google Play提交了一个版本
提示如下：
Issue found: Missing or Incomplete Declaration
We were unable to review your app because the information you provided in the console declaration was insufficient to evaluate the app for compliance with the VpnService requirements.

Additionally, follow these steps to bring your app into compliance:

Please fill up all the fields in the Declaration Form. Starting 31 August 2023, we will start blocking app updates, if the information you provided in the console is insufficient.
If your app does not require VpnService, please remove the relevant service element from the app manifest, for all artifacts across all release tracks.

我在主工程的AndroidManifest.xml添加了<uses-permission
        android:name="android.permission.BIND_VPN_SERVICE"
        tools:node="remove" />貌似没解决根本问题
应该移除SDK中AndroidManifest.xml的
 <service
            android:name="com.fvbox.lib.client.proxy.ProxyVpnService"
            android:enabled="true"
            android:exported="false"
            android:permission="android.permission.BIND_VPN_SERVICE" >
            <intent-filter>
                <action android:name="android.net.VpnService" />
            </intent-filter>

            <meta-data
                android:name="android.net.VpnService.SUPPORTS_ALWAYS_ON"
                android:value="true" />
        </service>
但是主工程貌似移除不了SDK中AndroidManifest.xml注册的service，这怎么破？？？
