### ISSUE TITLE
google服务现在是不支持吗

### ISSUE THREAD

**Issue by godlikewangjun** [FSpaceCore/SpaceCore#41]
用app测试发现不支持google登录和支付

**Comment by jack20209527** [comment]
google play你上架能上去吗，我都提交不上去，sdk清单文件有问题，他设置了测试模式

**Comment by godlikewangjun** [comment]
> google play你上架能上去吗，我都提交不上去，sdk清单文件有问题，他设置了测试模式

aar很好改的，你自己覆盖不就行了吗？gms不支持我测试都不能测试

**Comment by FSpaceCore** [comment]
gms是不支持的

**Comment by jack20209527** [comment]
> aar很好改的，你自己覆盖不就行了吗？gms不支持我测试都不能测试

兄弟好，具体怎么覆盖，有相关文章吗，我找了不少资料还是不知道怎么弄，感谢指导下？付费也可以

**Comment by jack20209527** [comment]
弄好了，用tools:remove "android.debuggalbe"就行了，感谢godlikewangjun

**Comment by FSpaceCore** [comment]
暂时是不支持的

**Comment by dongbeicxy** [comment]
我在Google Play提交了一个版本
提示如下：
Issue found: Missing or Incomplete Declaration
We were unable to review your app because the information you provided in the console declaration was insufficient to evaluate the app for compliance with the VpnService requirements.

Additionally, follow these steps to bring your app into compliance:

Please fill up all the fields in the Declaration Form. Starting 31 August 2023, we will start blocking app updates, if the information you provided in the console is insufficient.
If your app does not require VpnService, please remove the relevant service element from the app manifest, for all artifacts across all release tracks.

我在主工程的AndroidManifest.xml添加了貌似没解决根本问题
应该移除SDK中AndroidManifest.xml的



        <meta-data
            android:name="android.net.VpnService.SUPPORTS_ALWAYS_ON"
            android:value="true" />
    </service>
但是主工程貌似移除不了SDK中AndroidManifest.xml注册的service，这怎么破？？？
